import "@/styles/globals.css"
  // here @/ refer to root dir as defined in jsconfig.json file

// Below code are auto generated by next.js once app ran (we'll tweak it as per required.)
export const metadata = {
  title: 'Promptopia',
  description: 'Discover & Share AI prompts.',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
        <div className="main">
          <div className="gradient"></div>
        </div>
        <main className="app">
        {children}
        </main>
      </body>
    </html>
  )
}
