import "@/styles/globals.css"
import Nav from '@/components/Nav';
  // here @/ refer to root dir as defined in jsconfig.json file

import Provider from "@/components/Provider";
  // importing Provider to use contexts like session data as defined in Provider.jsx

// Below code are auto generated by next.js once app ran (we'll tweak it as per required.)
export const metadata = {
  title: 'Promptopia',
  description: 'Discover & Share AI prompts.',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
        <Provider>
          <div className="main">
            <div className="gradient"></div>
          </div>
          <main className="app">
          <header className="w-full">
            <Nav />
          </header>
          {children}
          </main>
        </Provider>
        {/* wrapping body content by Provider to provide contexts data to them */}
      </body>
    </html>
  )
}
